
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

  install:
    - pip install -r doc/requirements.txt  # 告诉 Read the Docs 安装这些包


sphinx:
   configuration: doc/source/conf.py


        